# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompanyMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.TipaMap = QtWidgets.QLabel(Form)
        self.TipaMap.setGeometry(QtCore.QRect(50, 50, 500, 500))
        self.TipaMap.setObjectName("TipaMap")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(580, 130, 291, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.DeceleratoButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DeceleratoButton.setObjectName("DeceleratoButton")
        self.gridLayout.addWidget(self.DeceleratoButton, 2, 1, 1, 1)
        self.ShieldButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ShieldButton.setObjectName("ShieldButton")
        self.gridLayout.addWidget(self.ShieldButton, 3, 0, 1, 1)
        self.FighterButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.FighterButton.setObjectName("FighterButton")
        self.gridLayout.addWidget(self.FighterButton, 0, 1, 1, 1)
        self.ShooterButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ShooterButton.setObjectName("ShooterButton")
        self.gridLayout.addWidget(self.ShooterButton, 0, 0, 1, 1)
        self.ProvacateurButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ProvacateurButton.setObjectName("ProvacateurButton")
        self.gridLayout.addWidget(self.ProvacateurButton, 1, 1, 1, 1)
        self.AssasinButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AssasinButton.setObjectName("AssasinButton")
        self.gridLayout.addWidget(self.AssasinButton, 2, 0, 1, 1)
        self.ClearUnits_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ClearUnits_2.setObjectName("ClearUnits_2")
        self.gridLayout.addWidget(self.ClearUnits_2, 3, 1, 1, 1)
        self.SniperButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SniperButton.setObjectName("SniperButton")
        self.gridLayout.addWidget(self.SniperButton, 1, 0, 1, 1)
        self.NotificationLabel = QtWidgets.QLabel(Form)
        self.NotificationLabel.setGeometry(QtCore.QRect(50, 20, 821, 31))
        self.NotificationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NotificationLabel.setObjectName("NotificationLabel")
        self.StartGameButton = QtWidgets.QPushButton(Form)
        self.StartGameButton.setGeometry(QtCore.QRect(580, 430, 291, 41))
        self.StartGameButton.setObjectName("StartGameButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(584, 65, 281, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.GoBackButton = QtWidgets.QPushButton(Form)
        self.GoBackButton.setGeometry(QtCore.QRect(580, 500, 291, 41))
        self.GoBackButton.setObjectName("GoBackButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Simulator Of Battle: Company Mode"))
        self.TipaMap.setText(_translate("Form", "TextLabel"))
        self.DeceleratoButton.setText(_translate("Form", "Decelerator [4]"))
        self.ShieldButton.setText(_translate("Form", "Shield [8]"))
        self.FighterButton.setText(_translate("Form", "Fighter [4]"))
        self.ShooterButton.setText(_translate("Form", "Shooter [5]"))
        self.ProvacateurButton.setText(_translate("Form", "Provocateur [5]"))
        self.AssasinButton.setText(_translate("Form", "Assasin [6]"))
        self.ClearUnits_2.setText(_translate("Form", "Clear"))
        self.SniperButton.setText(_translate("Form", "Sniper [10]"))
        self.NotificationLabel.setText(_translate("Form", "[]"))
        self.StartGameButton.setText(_translate("Form", "Start Game"))
        self.label.setText(_translate("Form", "Money: NULL"))
        self.GoBackButton.setText(_translate("Form", "Go Back"))
