# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenuUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.NameOfGame = QtWidgets.QLabel(Form)
        self.NameOfGame.setGeometry(QtCore.QRect(100, 80, 700, 200))
        font = QtGui.QFont()
        font.setFamily("Intro ")
        font.setPointSize(36)
        self.NameOfGame.setFont(font)
        self.NameOfGame.setAlignment(QtCore.Qt.AlignCenter)
        self.NameOfGame.setObjectName("NameOfGame")
        self.StartGameButton = QtWidgets.QPushButton(Form)
        self.StartGameButton.setGeometry(QtCore.QRect(300, 310, 300, 51))
        self.StartGameButton.setObjectName("StartGameButton")
        self.QuitButton = QtWidgets.QPushButton(Form)
        self.QuitButton.setGeometry(QtCore.QRect(300, 430, 300, 51))
        self.QuitButton.setObjectName("QuitButton")
        self.AllUnitsButton = QtWidgets.QPushButton(Form)
        self.AllUnitsButton.setGeometry(QtCore.QRect(300, 370, 300, 51))
        self.AllUnitsButton.setObjectName("AllUnitsButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Simulator Of Battle"))
        self.NameOfGame.setText(_translate("Form", "Simulator Of Battle\n[light]"))
        self.StartGameButton.setText(_translate("Form", "Start Game"))
        self.QuitButton.setText(_translate("Form", "Quit"))
        self.AllUnitsButton.setText(_translate("Form", "About Units"))
